services:
  minecraft-modpack:
    image: eclarift/minecraft-modpack:latest
    container_name: minecraft-modpack
    env_file:
      - .env
    ports:
      - "25565:25565"
    volumes:
      - minecraft-data:/minecraft
      - ./data/world:/minecraft/world
      - ./data/logs:/minecraft/logs

      - ./data/config:/config

      - ./data/mods/jars:/minecraft/mods
      - ./data/mods/config:/minecraft/config
      - ./
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  minecraft-data:
    driver: local
